### ISSUE TITLE
Guide to install and use on OMV 3.X

### ISSUE THREAD

**Issue by dcbasso** [OpenMediaVault-Plugin-Developers/openmediavault-openvpn#15]
Please, it´s possible to add to thre README the guide to install this plugin on OMV 3.X?
thanks

**Comment by ryecoaaron** [comment]
Do you mean how to install the plugin or how to configure the plugin?

**Comment by dcbasso** [comment]
Install this plugin. I got one package but is for OMV 1.X and I got problems.
I would like to use this OPENVPN on OMV 3.X, could you help me with that?

**Comment by ryecoaaron** [comment]
Install omv-extras for OMV 3.x following this guide - http://omv-extras.org/joomla/index.php/guides
Then go to the Plugins tab and click Check.  The plugin should be listed for install there after that.

**Comment by dcbasso** [comment]
Well VPN only appears to have version 1.1, thats correct?

**Comment by dcbasso** [comment]
After "apt clean" the problem was solved.
Appears the 3.0.6 version of OpenVNC.
Thanks so much, could close this "issue".

**Comment by dcbasso** [comment]
Another question, I got this error:
"Missing 'required' attribute 'gateway_interface', but I couldn't found this field!

**Comment by dcbasso** [comment]
It's not possible to generate cert to users.

**Comment by ryecoaaron** [comment]
Did you login to the omv web interface as a user (other than admin)?  I think that is where you generate certs but I don't use the plugin.  This would be better to figure out in the forum where lots of users can see the question.
