### ISSUE TITLE
Missing "gateway_interface" on OpenVPN setup page

### ISSUE THREAD

**Issue by dcbasso** [OpenMediaVault-Plugin-Developers/openmediavault-openvpn#16]
The page to setup OpenVPN is missing the field "gateway_interface", as we can check here:
Check post here: https://forum.openmediavault.org/index.php/Thread/17380-Setting-Vpn-to-access-from-outside/?postID=163458#post163461

I API is waiting a payload json with the attribute "gateway_interface" but the screen is not sending this attr to the API, so we got an error.

I think it's a bug! I try to send the same post with the correct payload and the setup openvpn works!

**Comment by ryecoaaron** [comment]
The javascript is there.  Closing since I think this is related to your system and we can figure that out in the forum thread.
