### ISSUE TITLE
Invalid configuration file when having multiple routes for the same interface

### ISSUE THREAD

**Issue by EzequielB** [OpenMediaVault-Plugin-Developers/openmediavault-openvpn#24]
When there are multiple routes for the same interface an invalid openvpn configuration is produced. This seems to be produces in some cases (https://bbs.archlinux.org/viewtopic.php?id=185043)
```
$ ip r s
default via 10.0.1.1 dev enx001e06367972 
10.0.1.0/24 dev enx001e06367972 proto kernel scope link src 10.0.1.4
10.0.1.0/24 dev enx001e06367972 proto kernel scope link src 10.0.1.4 metric 100 
10.8.0.0/24 dev tun0 proto kernel scope link src 10.8.0.1 
169.254.0.0/16 dev tun0 scope link metric 1000 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
```
This produces an invalid subnet value and invalid configuration file:
```
;push "route 10.0.1.0
10.0.1.0 255.255.255.0"
```

**Comment by theOehrly** [comment]
Will there be a new version released soon, so one can easily update the plugin? That would be good I think. Because there are already guides online on "Howto setup OpenVPN on OMV despite bug" (title paraphrased)

**Comment by ryecoaaron** [comment]
I just updated the plugin with the merge listed above.
