### ISSUE TITLE
Error when try to add a new cert (OpenVPN 4.0.4)

### ISSUE THREAD

**Issue by juanillo62gm** [OpenMediaVault-Plugin-Developers/openmediavault-openvpn#26]
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-mkconf openvpn add '776ed744-e40e-4faf-be9c-6a630650adee' 2>&1' with exit code '1': Easy-RSA error: EASYRSA_PKI does not exist (perhaps you need to run init-pki)? Expected to find the EASYRSA_PKI at: /etc/openvpn/pki Run easyrsa without commands for usage and command help.

Error #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-mkconf openvpn add '776ed744-e40e-4faf-be9c-6a630650adee' 2>&1' with exit code '1': 
Easy-RSA error:

EASYRSA_PKI does not exist (perhaps you need to run init-pki)?
Expected to find the EASYRSA_PKI at: /etc/openvpn/pki
Run easyrsa without commands for usage and command help. in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/openmediavault/engined/rpc/openvpn.inc(209): OMV\System\Process->execute()
#1 [internal function]: OMV\Engined\Rpc\OpenVpn->set(Array, Array)
#2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#3 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('set', Array, Array)
#4 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('OpenVpn', 'set', Array, Array, 1)
#5 {main}

**Comment by madhub0815** [comment]
How to solve this? Got the same error?

**Comment by ryecoaaron** [comment]
If you are getting the same error, you are using OMV 4.x or older and this is no supported anymore.
