### ISSUE TITLE
Single file configuration for OpenVPN

### ISSUE THREAD

**Issue by cerces** [OpenMediaVault-Plugin-Developers/openmediavault-openvpn#7]
Support inline inclusion of certificate/tls-auth/key/CA in the configuration file so as to have a unique configuration file.
Description of the feature : https://community.openvpn.net/openvpn/wiki/Openvpn23ManPage#lbAV

**Comment by subzero79** [comment]
A developer is currently working in a plugin redesign, it will also include
the inline or embedded certificate in the .conf or ovpn file. You just have
to wait for the plugin to become available for testing (not repo). Probably
around two weeks from now.
